env:
  global:
  - CC_TEST_REPORTER_ID=c74f1ea872b30b6251dac95db5cdd985ab63afea6121ca21807d2dfd801cfc0c
language: node_js
node_js:
- stable
services:
  - mongodb
cache:
  directories:
  - node_modules
before_script:
- npm install
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm test
- npm run coveralls
- npm run codeClimate
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
